### ISSUE TITLE
Can't see the logs when trying to use OpenID Connect

### ISSUE THREAD

**Issue by brvalenc** [opensearch-project/security-dashboards-plugin#108]
Is there an option to see the logs or debugging when an OpenID Integration is trying to be achieved? I'm trying to integrate my ELK with a SSO by OpenID Connect but the only message I can see is:
"plugin:opendistro_security@7.2.0 | An error occurred during initialisation, please check the logs" when I start Kibana, and I can't see those logs anywhere...

My config.yml (in Elasticsearch):
```
---

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: noop
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://sso.sso-app-demo.svc:8443/auth/realms/master/.well-known/openid-configuration
        authentication_backend:
          type: noop

```

My kibana.yml
```server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "https://elasticsearch-opendistro.elasticsearch-lab2.svc:9200" ]

# Enable OpenID authentication
opendistro_security.auth.type: "openid"
#
## The IdP metadata endpoint
opendistro_security.openid.connect_url: "https://sso.sso-app-demo.svc:8443/auth/realms/master/.well-known/openid-configuration"
#
## The ID of the OpenID Connect client in your IdP
opendistro_security.openid.client_id: "client-kibana"
#
## The client secret of the OpenID Connect client
opendistro_security.openid.client_secret: "7f9529e3-51aa-4d05-9f2c-4b78e60abb14"
#
## Configure the Kibana internal server user
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
#
## Disable SSL verification when using self-signed demo certificates
elasticsearch.ssl.verificationMode: none
#
## Whitelist basic headers and multi-tenancy header
elasticsearch.requestHeadersWhitelist: ["Authorization", "security_tenant", "securitytenant"]

#
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
```

I've tried to increse the log4j log levels like this:
```logger.opendistro_security.name = com.amazon.opendistroforelasticsearch.security
logger.opendistro_security.level = trace
logger.opendistro_security.appenderRef.rolling.ref = rolling 
logger.opendistro_security.appenderRef.rolling_old.ref = rolling_old 
logger.opendistro_security.additivity = false
```

But it didn't work, even Elasticsearch shows these messages:
```
2019-10-24 15:46:31,854 main ERROR Unable to locate appender "rolling " for logger config “com.amazon.opendistroforelasticsearch.security”
2019-10-24 15:46:31,856 main ERROR Unable to locate appender "rolling_old " for logger config
```

I appreciate your help a lot.

Thanks.
