### ISSUE TITLE
[BUG] "Log in with single sign-on" button redirects to incorrect URL

### ISSUE THREAD

**Issue by m-shalenko** [opensearch-project/security-dashboards-plugin#1357]
**What is the bug?**
I use a custom `server.basePath` and `server.rewriteBasePath: true`, enable the multiple auth types `opensearch_security.auth.type: ["basicauth", "openid"]`. If I click openid sign-on button I will be redirected to `http://<hostname>:5601/auth/openid/login`, not `http://<hostname>:5601/<basePath>/auth/openid/login`. The same situation happens whether I use a reverse proxy (nginx). By the way, if I leave only one auth type `openid` It works fine because at this case there is no button.

1) I attach opensearch-dashboards configuration
```yaml
# Please do not change this file directly since it is managed by Ansible and will be overwritten
server.host: 0.0.0.0
server.port: 5601
opensearch.hosts: ['https://192.168.*.*:9200']

logging.dest: /var/log/opensearch-dashboards/opensearch-dashboards.log
logging.rotate:
  enabled: true
  everyBytes: 10485760
  keepFiles: 10
opensearch.password: ****
opensearch.requestHeadersAllowlist:
- Authorization
- security_tenant
opensearch.ssl.verificationMode: none
opensearch.username: kibanaserver
opensearch_security.auth.multiple_auth_enabled: true
opensearch_security.auth.type:
- basicauth
- openid
opensearch_security.cookie.secure: false
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred:
- Private
- Global
opensearch_security.openid.base_redirect_url: https://opensearch-dashboards.example.com/opensearch-logging-dev
opensearch_security.openid.client_id: oidc
opensearch_security.openid.client_secret: ****
opensearch_security.openid.connect_url: https://auth.example.com/realms/example/.well-known/openid-configuration
opensearch_security.openid.trust_dynamic_headers: true
opensearch_security.readonly_mode.roles:
- kibana_read_only
opensearch_security.ui.openid.login.buttonname: Log in with single sign-on (OIDC)
server.basePath: /opensearch-logging-dev
server.rewriteBasePath: true
```
2) opensearch-security/config.yml
```yaml
---
# Please do not change this file directly since it is managed by Ansible and will be overwritten
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        authentication_backend:
          type: internal
        http_authenticator:
          challenge: false
          type: basic
        http_enabled: true
        order: 0
        transport_enabled: true
      openid_auth_domain:
        authentication_backend:
          type: noop
        http_authenticator:
          challenge: false
          config:
            openid_connect_idp:
              enable_ssl: true
              pemtrustedcas_filepath: /etc/opensearch/openid-ca.pem
              verify_hostnames: false
            openid_connect_url: https://auth.example.com/realms/example/.well-known/openid-configuration
            roles_key: roles
            subject_key: preferred_username
          type: openid
        http_enabled: true
        order: 1
        transport_enabled: true
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
```
3) NGINX config
```
upstream opensearch_logging_dev {
  server 192.168.*.*:5601;
}

server {
  listen [::]:80 ipv6only=off;
  server_name openseaerch-dashboards.example.com;
  return 301 https://$host$request_uri;
}
server {
  listen [::]:443 ssl ipv6only=off;

  server_name openseaerch-dashboards.example.com;

  ssl_certificate ssl/openseaerch-dashboards.example.com.crt;
  ssl_certificate_key ssl/openseaerch-dashboards.example.com.key;

  access_log  /var/log/nginx/openseaerch-dashboards.example.com.access.log main;
  error_log   /var/log/nginx/openseaerch-dashboards.example.com.error.log;

  location /opensearch-logging-dev {
    proxy_pass http://opensearch_logging_dev;
  }

  location / {
    return 404;
  }
}

```

**How can one reproduce the bug?**
1. Define `server.basePath`, `server.rewriteBasePath` to `true`, and `opensearch_security.auth.type` to `["basicauth", "openid"]` as I have yet defined above.
2. Click on the button "Log in with single sign-on" and you will get 404 error

**What is the expected behavior?**
I expect the redirect url has to be `http://<hostname>/<basePath>/auth/openid/login`.

**What is your host/environment?**
 - Ubuntu 20.04
 - OpenSearch 2.5.0 (checked 2.6.0 as well and the behaviour is the same)
