### ISSUE TITLE
No access to security features when using own defined full access admin role

### ISSUE THREAD

**Issue by jakubbujny** [opensearch-project/security-dashboards-plugin#15]
Kibana version in docker: amazon/opendistro-for-elasticsearch-kibana:0.8.0
Elasticsearch version in docker: amazon/opendistro-for-elasticsearch:0.8.0 

Reproduction:

1. Activate OpenID SSO in Kibana: 
```
# Enable OpenID authentication
opendistro_security.auth.type: "openid"

# The IdP metadata endpoint
opendistro_security.openid.connect_url: "https://my-keycloak.com"

# The ID of the OpenID Connect client in your IdP
opendistro_security.openid.client_id: "kibana"

# The client secret of the OpenID Connect client
opendistro_security.openid.client_secret: "secret"

```
2. Activate SSO in Elasticsearch according to documentation:
```
authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      openid_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://my-keycloak.com/auth/realms/master/.well-known/openid-configuration
```
3. In KeyCloak add role to user called: my_own_admin_keycloak
4. Define my_own_admin_kibana role in Kibana by cloning all_access role
5. Define role mapping my_own_admin_keycloak backend role  -> my_own_admin_kibana

After those operations when I login with user which has my_own_admin_keycloak role I have full access to all regular features in Kibana/Elasticsearch. The only one thing to which I don't have access is Security sections - all buttons disappear and I can see only Authentication & Authorization button but when I'm trying to get into that section I see javascript errors in webconsole.

To fix that I need to add "admin" role to my user in KeyCloak so then I have full access to all features but I want to avoid adding "admin" role to my users as it gives also permissions in some other services in our company.
