### ISSUE TITLE
[FEATURE] Dynamic multiple authentication

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1573]
**Is your feature request related to a problem?**

Since OS 2.4, the security-dashboards-plugin has supported having multiple login options from the login screen: https://github.com/opensearch-project/security-dashboards-plugin/pull/1110

Configuring multi auth is done via settings in `opensearch_dashboards.yml`. Example:

```
opensearch_security.auth.type: ["basicauth","openid"]
opensearch_security.auth.multiple_auth_enabled: true
```

Since these settings are defined in `opensearch.yml` its not possible to change the configuration without restarting OpenSearch-Dashboards. It could be useful to make these settings dynamic to allow cluster admins to change these settings without having to restart dashboards.

**What solution would you like?**

Allow cluster admins to change multi-auth settings dynamically

**Do you have any additional context?**

A similar feature was implemented for multi-tenancy: https://github.com/opensearch-project/security-dashboards-plugin/issues/1302

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks thank you for filing this issue. Going to tag this help wanted for the time being.

**Comment by cwperks** [comment]
Here's a screenshot where 2 authenticators are configured for OpenSearch-Dashboards.

![Screenshot 2023-10-26 at 4 22 01 PM](https://github.com/opensearch-project/security-dashboards-plugin/assets/17432265/39db88e4-f52d-4990-b2b8-baa069553537)

This is Basic Auth + SAML for logging into dashboards. Here's a zip of the configuration as well.

[2.10.0-saml-plus-basic-multiauth.zip](https://github.com/opensearch-project/security-dashboards-plugin/files/13383265/2.10.0-saml-plus-basic-multiauth.zip)

The outcome of this issue will be to dynamically change what is shown on the login screen. Through the admin page an admin could configure login with basic + SAML, or remove the option to login with SAML and just have basic (username + pw), or remove basic and have login with SAML by itself (in which case the login screen won't appear and a user will be re-directed to the SAML IdP's login screen). 

Any change would be dynamic and not require a reboot of OSD.

**Comment by cwperks** [comment]
Not all combinations of multi-auth may be valid initially. Its possible to have multiple single-sign on buttons, but the prompt for username and pw can only appear once.

The prompt for username and pw is shown when OSD is configured either with:

- Basic Internal Auth
- LDAP auth

Single sign on would apply to SAML and OIDC. Other auth types would not go through the sign in screen and are out of scope. Other auth types include clientcert, proxy and jwt.

Only the following combinations of auth types are valid to configure for multiauth:

1. basic or ldap
2. one or more of saml or oidc

**Comment by davidosorno** [comment]
@EduardoCorazon and I are working on this feature and I proposed the following UX/UI design

![Screenshot from 2023-11-15 09-52-57](https://github.com/opensearch-project/security-dashboards-plugin/assets/48450162/437eb514-af52-4cae-becf-76410bd1ab77)

However @cwperks mentioned  that "`Not all combinations of multi-auth can be done iirc.`
`I believe you can only select up to 2 and it would need to be the following combinations:`
`basic or ldap`
`one or more of saml or oidc`" [multi auth documentation](https://opensearch.org/docs/latest/security/configuration/multi-auth).
We'll post some UX/UI ideas and I hope @kamingleung can help us here too to create a good user experience.

**Comment by EduardoCorazon** [comment]
Here's a little updated design based on the original
<img width="1210" alt="image" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/79670342/8ee8468a-966a-4e61-8e54-70ccef1671aa">

**Comment by cwperks** [comment]
Thank you for posting the mockups @davidosorno and @EduardoCorazon. The UX will need to reflect what valid combos a user can choose from for showing login options on the login screen. There are 2 broad categories:

1. Username and pw entry on OSD login screen (This is the case for Basic internal auth and LDAP)
2. SSO button - when a user clicks the SSO button they are re-directed outside of OSD to their identity provider's login screen. On successful login they are re-directed back to OSD. (SAML and OIDC)

Valid combos are:

1. One of Basic Internal auth or OIDC
2. One or more of SAML / OIDC
3. Other authenticators should not be displayed because they are options for programmatically connecting to OpenSearch and not for logging into OSD. JWT is a bit of an exception, but with jwt you pass a url param like `https://localhost:5601/app/dashboards?token=<jwt>` and never actually have to hit the login screen.

**Comment by kamingleung** [comment]
@cwperks, a few follow-up questions:
1. What are some of invalid examples / edge cases? 
2. Does multiple auth is only support 3 types: Basic, OIDC, SAML? Assuming a user can select Anonymous as a single auth method, then if a user enables multi auth, does it mean the Anonymous auth will be disabled?
3. What happens if the admin deselect a method that the admin is currently used to login to the instance? Are there mechanisms to prevent getting locked out?
4. What are the end-to-end steps for an admin to setup authentication? Is it: first select SAML as a method, then go to a config file to config SAML, any other steps?

**Comment by cwperks** [comment]
Thank you @kamingleung. See my answers below. The documentation on multi-auth on the documentation website is pretty extensive: https://opensearch.org/docs/latest/security/configuration/multi-auth/

1. This feature would not enable or disable the authenticators of the backend, but only change how the login screen for OSD would present. There must be at least 1 login method for OSD defined at any given time. Basic could be configured at most once, anonymous at most once, but for SAML and OIDC there (theoretically) could be many. I have to double check the implementation of multi-auth, but there may already be a restriction of 1 per type.

2. @kamingleung Anonymous login can be a button similar to the SSO button. See Priscilla's post on the OpenSearch forum here to see an example of `Log in as Anonymous`: https://forum.opensearch.org/t/anonymous-user-multiple-authentication/11577/2?u=cwperks

3. Simply toggling to enable dynamic multi-auth would not change the existing login screen. The login screen would only change if the admin made a change to select multiple login options for the login screen. The second part to this question is a good question. There will always need to be a way to login into dashboards so a user cannot remove all login methods. A cluster admin could always use [securityadmin](https://opensearch.org/docs/2.11/security/configuration/security-admin/) to re-enable other login methods for OSD.

4.  Typically setup is done through [yaml files](https://opensearch.org/docs/latest/security/configuration/configuration/) before initial cluster startup. The yaml files we ship with has many examples of configs for different types of identity providers, but ultimately its up to a cluster admin to finish the configuration. Sometimes setup requires a lot of trial and error before a user is able to successfully get OpenSearch and OSD configured with SSO. Setting up multi auth means configuring multiple authentication backends in the security plugins `config.yml` file like this:

```
config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              entity_id: http://localhost:8080/simplesaml/saml2/idp/metadata.php
              metadata_url: http://localhost:8080/simplesaml/saml2/idp/metadata.php?output=xml
            sp:
              entity_id: opensearch-dashboards
            kibana_url: http://localhost:5601/
            roles_key: Role
            subject_key: NameID
            exchange_key: '<exchange_key>'
```

and also configuring `opensearch-dashboards.yml` to enable both login with username/pw or SSO with SAML.

```
opensearch_security.auth.type: ["basicauth", "saml"]
opensearch_security.auth.multiple_auth_enabled: true
```

with this feature, an admin would be able to dynamically change whether the SSO button appears on the login screen w/o having to change the `opensearch_dashboards.yml` file and restart the OSD node.

What I would like to do in the future is be able to start a cluster with Basic Authentication and then configure another SSO provider like SAML or OIDC directly in OpenSearch Dashboards.
