### ISSUE TITLE
Session timeout in Kibana SAML

### ISSUE THREAD

**Issue by snarmaev** [opensearch-project/security-dashboards-plugin#159]
Hello, I have the same issue with the expiring session time in Kibana. However, I have set options to keep session for 24 hours in kibana.yml

opendistro_security.cookie.ttl: 86400000
opendistro_security.session.ttl: 86400000
opendistro_security.session.keepalive: true

Could you please help with this issue?

**Comment by Thoro** [comment]
It seems SAML does not adhere to the set session timeouts and always uses 1 h by default, and disabled keepalive ...https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/88f7dd343e53fabc466f92b90a9165db105d9b7b/lib/auth/types/saml/Saml.js#L70

**Comment by snarmaev** [comment]
@Thoro  Thank you for your suggestion. However, I am getting the following error:

`ERR: Seems /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml is not in Open Distro Security 7 format: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "jwt" (class com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7), not marked as ignorable (one known property: "dynamic"])`

**Comment by Thoro** [comment]
should look like that:

```
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_file: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/metadata.xml
              enable_ssl: true
              verify_hostnames: true
              entity_id: https://xxxx
            sp:
              entity_id: https://xxxx
            kibana_url: https://xxxx
            roles_key: Role
            exchange_key:xxxx
            jwt:
              expiry: AUTO+1440
        authentication_backend:
          type: noop
```
