### ISSUE TITLE
[BUG] Security cookie could be too large when using JWT auth type

### ISSUE THREAD

**Issue by pheex** [opensearch-project/security-dashboards-plugin#1638]
**What is the bug?**
When using JWT auth type, security cookie is too large if JWT token is big, browser refuse to store it (more than 4kb)  looks like https://github.com/opensearch-project/security-dashboards-plugin/pull/1352 is not applied to JWT auth type

**How can one reproduce the bug?**
Use this configuration
security-config : i use openid config only to get JWKS keyring

```
    openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            openid_connect_idp:
              enable_ssl: true
              verify_hostnames: false
              pemtrustedcas_filepath: "/usr/share/opensearch/config/ca.crt"
            subject_key: preferred_username
            roles_key: flatten_ressources_access
            jwks_uri: {{getv "/keycloak/url"}}/realms/{{getv "/keycloak/realm"}}/protocol/openid-connect/certs
        authentication_backend:
          type: noop
      jwt_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: jwt
          challenge: false
          config:
            jwt_header: "Authorization"
            subject_key: preferred_username
            roles_key: flatten_ressources_access
            jwt_clock_skew_tolerance_seconds: 20
        authentication_backend:
          type: noop
```

opensearch_dashboard.yml
```
opensearch_security.auth.type: "jwt"
opensearch_security.jwt.url_param: "token"
```

**What is the expected behavior?**
Cookie should be splitted

**What is your host/environment?**
opensearch 2.11.0
opensearch dashboard 2.11.0
