### ISSUE TITLE
_bulk_get returns 404, even though find returns the correct ids

### ISSUE THREAD

**Issue by Thoro** [opensearch-project/security-dashboards-plugin#166]
Hello,

I have a very limited role:

```
access_limited:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "kubernetes-*"
    dls: "{\r\n\t\t\"bool\": {\r\n\t\t\t\"must\": [\r\n\t\t\t\t{\r\n\t\t\t\t\t\"query_string\": {\r\n\t\t\t\t\t\t\"query\": \"location:42\"\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t]\r\n\t\t}\r\n\t}"
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  - index_patterns:
    - "logstash-*"
    dls: "{\r\n\t\t\"bool\": {\r\n\t\t\t\"must\": [\r\n\t\t\t\t{\r\n\t\t\t\t\t\"query_string\": {\r\n\t\t\t\t\t\t\"query\": \"(location:47 OR location:62)\"\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t]\r\n\t\t}\r\n\t}"
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions:
  - tenant_patterns:
    - "Limited"
    allowed_actions:
    - "kibana_all_read"
    - "kibana_all_write"
```

The user assigned to this role, is correctly can correctly see the Index Patterns in kibana, but once the _bulk_get api is called, it returns 404 Not Found:

```
GET /api/saved_objects/_find?fields=title&per_page=10000&type=index-pattern

Response:
{"page":1,"per_page":10000,"total":2,"saved_objects":[{"type":"index-pattern","id":"21d5ed50-7f0a-11ea-9019-e33eb18b69fd","attributes":{"title":"kubernetes-*"},"references":[],"migrationVersion":{"index-pattern":"7.6.0"},"updated_at":"2020-04-15T11:13:30.425Z","version":"WzEzLDFd"},{"type":"index-pattern","id":"3de96d50-7f0a-11ea-9019-e33eb18b69fd","attributes":{"title":"logstash-*"},"references":[],"migrationVersion":{"index-pattern":"7.6.0"},"updated_at":"2020-04-15T11:14:22.623Z","version":"WzE1LDFd"}]}
```

```
POST /api/saved_objects/_bulk_get

Request:
[{"id":"21d5ed50-7f0a-11ea-9019-e33eb18b69fd","type":"index-pattern"}]

Response:
{"saved_objects":[{"id":"21d5ed50-7f0a-11ea-9019-e33eb18b69fd","type":"index-pattern","error":{"statusCode":404,"message":"Not found"}}]}
```

For a user with full access permissions, this issue does not  happen. If the error is happening, then the Discover functionality is not working anymore.
