### ISSUE TITLE
[FEATURE] Multi-auth dashboards support for JWT

### ISSUE THREAD

**Issue by 10000-ki** [opensearch-project/security-dashboards-plugin#1814]
**Is your feature request related to a problem?**

**What solution would you like?**

Hello

we can set order of auth in `opensearch`

```yml
config:
      dynamic:
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: false

        authc:
          # oidc with jwks_uri
          jwks_auth_domain:
            description: "Authenticate via JWKS"
            http_enabled: true
            transport_enabled: false
            order: 0
            http_authenticator:
              type: openid
              challenge: false
              config:
                jwt_header: "Authorization"
                jwt_url_parameter: null
                subject_key: "sub"
                roles_key: "scp"
                jwks_uri: {{ jwksUri }}
            authentication_backend:
              type: noop

          # basic auth, using internal user db
          basic_internal_auth_domain:
            description: "Authenticate using HTTP basic against the internal users database"
            http_enabled: true
            transport_enabled: false
            order: 1
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: internal
```

but dashboards not

so In dashboards, jwt and basic_auth cannot be used simultaneously

**What alternatives have you considered?**

**Do you have any additional context?**
