### ISSUE TITLE
[FEATURE] Support configuring auth_failure_listeners through Dashboards

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#2070]
**Is your feature request related to a problem?**

The OpenSearch Security plugin has a useful feature called [auth_failure_listeners](https://opensearch.org/docs/latest/security/configuration/api-rate-limiting/) that allows cluster administrators to block requests after a certain number of requests fail authentication in a window of time. Currently, there are 2 types of auth_failure_listeners: 1) IP-based and 2) username-based. 

See example below, for configuring an auth_failure_listener based on username that will block requests for 60 seconds if 3 requests fail authentication within a 60 second window: 

```
auth_failure_listeners:
  internal_authentication_backend_limiting:
    type: username
    authentication_backend: internal
    allowed_tries: 3
    time_window_seconds: 60
    block_expiry_seconds: 60
    max_blocked_clients: 100000
    max_tracked_clients: 100000
```

Currently, cluster administrators can only configure these rate limiters through the config.yml file meaning they either need to configure it 1) Before cluster initialization, 2) Using securityadmin.sh or 3) through the security API using an admin cert

This feature of the Security plugin should have associated UX to make the feature more discoverability and to make it easy to configure for administrators.
