### ISSUE TITLE
Keycloak auth

### ISSUE THREAD

**Issue by hkroger** [opensearch-project/security-dashboards-plugin#21]
I'm trying to do keycloak auth and I have setup everything for it.

I have client id and browser authentication flow working seemingly ok. Keycloak logs show that appropriate code-to-token API is being called with correct authentication and all. But for some reason Kibana is still giving me error like this in the browser:

"Authentication failed. Please provide a new token." 

What could possibly be the reason for this?

I don't see too many debug logging options for openid auth nor bell itself so I am in the dark with this.

**Comment by hkroger** [comment]
I saw at least 8 places where there is a redirect to "customerror?type=authError" of which just 1 additionally logs something to server logs...

It makes it quite difficult to debug what goes wrong.

**Comment by mkjoerg** [comment]
I have the same problem with Keycloak OpenID Connect. Without additional log information this is a very painful process.

**Comment by NikitaGl** [comment]
Experiencing almost the same problem on Elasticsearch v7.3.2 with opendistro-security-v1.3.0.
The only difference is that it seems that I'm successfully logging in, turning back from Keycloak with `state` and `session_state` and instantly redirected to `/customerror?type=authError` :


```
kibana_1       | {"type":"response","@timestamp":"2020-01-31T15:13:44Z","tags":[],"pid":6,"method":"get","statusCode":200,"req":{"url":"/customerror?type=authError","method":"get","headers":{"host":"kibana:5601","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","referer":"http://kibana:5601/auth/openid/login?state=cZUz6RmpPFU-5Qa-u8pSSV&session_state=1fa48175-ded8-4b45-83c4-805daa04c76b&code=02693504-77ac-441a-b4b2-519823e65ad6.1fa48175-ded8-4b45-83c4-805daa04c76b.3f12560b-c289-4c55-8b77-4545c27529c0","accept-encoding":"gzip, deflate","accept-language":"ru,uk;q=0.9,en;q=0.8,en-US;q=0.7"},"remoteAddress":"172.19.0.1","userAgent":"172.19.0.1","referer":"http://kibana:5601/auth/openid/login?state=cZUz6RmpPFU-5Qa-u8pSSV&session_state=1fa48175-ded8-4b45-83c4-805daa04c76b&code=02693504-77ac-441a-b4b2-519823e65ad6.1fa48175-ded8-4b45-83c4-805daa04c76b.3f12560b-c289-4c55-8b77-4545c27529c0"},"res":{"statusCode":200,"responseTime":31,"contentLength":9},"message":"GET /customerror?type=authError 200 31ms - 9.0B"}
```



The only strange thing I've noticed is that during this, ES node generates an warning log:


```
es1_1          | {"type": "server", "timestamp": "2020-01-31T15:27:15,447+0000", "level": "WARN", "component": "c.a.o.s.h.HTTPBasicAuthenticator", "cluster.name": "docker-cluster", "node.name": "es1", "cluster.uuid": "1eewda9NSU-zaYfcAWYBdw", "node.id": "i3bPVRdxSayItWSU26n9Og",  "message": "No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'"  }
```

**Comment by diegoep** [comment]
Experiencing the same problem using amazon/opendistro-for-elasticsearch-kibana:1.4.0 with Keycloak OpenID Connect. There's nothing additional in the log even using the TRACE level. 
Have you got any solutions for this?

**Comment by NikitaGl** [comment]
I managed to resolve my issue with headers, actually. Unfortunately I did it a couple of months ago and forgot to post solution here. All in all, my cluster works with basic auth through internal user db for applications and Keycloak OpenID for team access through Kibana. Attaching my current `config.yml` for opendistro and `kibana.yml`, hope it will help.

**config.yml:**
```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        description: "Authenticate via Keycloak OpenID"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://keycloak.example.com/auth/realms/example/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

**kibana.yml:**
```
# Default Kibana configuration for docker target
server.name: kibana
server.host: "kibana"
server.port: "5601"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.security.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.reporting.enabled: false
xpack.canvas.enabled: false
xpack.watcher.enabled: true
xpack.spaces.enabled: false

elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: secretpassword

elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization","jwtToken"]
opendistro_security.multitenancy.enabled: false
# opendistro_security.multitenancy.tenants.enable_global: true
# opendistro_security.multitenancy.tenants.enable_private: true
# opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
# opendistro_security.multitenancy.enable_filter: false

## Enable OpenID authentication
opendistro_security.auth.type: "openid"
## The IdP metadata endpoint
opendistro_security.openid.connect_url: "https://keycloak.example.com/auth/realms/example/.well-known/openid-configuration"
## The ID of the OpenID Connect client in your IdP
opendistro_security.openid.client_id: "kibana-sso"
## The client secret of the OpenID Connect client
opendistro_security.openid.client_secret: "xxxxxx-xxxx-xxxxx-xxxxx-xxxxxxxxxxxxx"

# logging.verbose: true
```
