### ISSUE TITLE
[BUG] OpenID sessions re-authentication every 5 minutes

### ISSUE THREAD

**Issue by JordanBarnartt** [opensearch-project/security-dashboards-plugin#2114]
**What is the bug?**
We have configured Opensearch and Opensearch Dashboards to use OpenID authentication through Duo.  However, every 5 minutes (so it seems, right on the dot), the application "refreshes" itself, briefly redirects through OpenID authentication URLs, then returns back to the webpage.  This refresh does not occur automatically, but rather when something in the UI is interacted with after the 5 minute timer has passed.  This reload can result in lost work as the page loads to whatever it's default state is (ex. if I am creating an index template, the site will reload back into `/app/opensearch_index_management_dashboards`, losing any unsaved work).  This occurs regardless of whether there was user activity in that 5 minute period.

**How can one reproduce the bug?**
1. Configure `opensearch-security/config.yml` as follows:
```yaml
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: username
            roles_key: roles
            openid_connect_url: <our url>
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

2. Configure `opensearch_dashboards.yml` as follows:
```yaml
server.host: "0.0.0.0"

opensearch_security.auth.type: "openid"
opensearch_security.openid.connect_url: <our url>
opensearch_security.openid.client_id: <our client ID>
opensearch_security.openid.client_secret: <our secret>
opensearch_security.openid.base_redirect_url: <our redirect url>

# I added these four settings as part of troubleshooting the issue.  They did not have any effect.
opensearch_security.cookie.ttl: 86400000
opensearch_security.session.ttl: 86400000
opensearch_security.session.keepalive: true
opensearch_security.openid.refresh_tokens: true
### 

opensearch.ssl.verificationMode: none
```

**What is the expected behavior?**
Activity should "reset" the reauthentication timer.  The amount of time before re-authentication should either be configurable or take from a setting provided by the IdP.

**What is your host/environment?**
 - OS: Opensearch running on Ubuntu 20.04, Opensearch Dashboards run via Docker using opensearchproject/opensearch-dashboards image.
 - Version 2.16.0
 - Plugins: Only those included as part of the default configuration.

**Do you have any additional context?**
This problems seems similar to those described in https://forum.opensearch.org/t/opensearch-dashboards-with-openid-auth-frequent-session-timeouts/15893, https://github.com/opensearch-project/security-dashboards-plugin/issues/71, and https://github.com/opensearch-project/security-dashboards-plugin/issues/1522.  However, the various proposed solutions do not work for us.

My plan is to temporarily disable OIDC auth for Dashboards, but I am willing to perform any troubleshooting that may help solve the issue.

**Comment by derek-ho** [comment]
Hello @JordanBarnartt, can you check this related issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/1966, we fixed a bug around refresh tokens in 2.15. Also, could you provide your IDP settings to see if this could possibly be a mis-configuration on the IDP side of things?

**Comment by JordanBarnartt** [comment]
Thanks for your attention, @derek-ho.  I double-checked that this was still occurring, and it is.  I had since enabled dual authentication using basic internal auth and OIDC.  I note that after the ~5 minutes is up, an OIDC user is kicked back to the log in screen.  This is different from the behaviour when only OIDC auth is enabled, which would cause a reload but would leave the user signed in.

We're using Duo as an IdP.  Here are screenshots of the relevant settings:
![image](https://github.com/user-attachments/assets/253fbc08-d433-456e-8c17-23278b4742b6)

![image](https://github.com/user-attachments/assets/fc4f5c38-2e68-48ba-b518-ff489c88f511)

**Comment by derek-ho** [comment]
@JordanBarnartt Can you take a look here: https://opensearch.org/docs/latest/security/authentication-backends/openid-connect/#opensearch-security-configuration? I think the issue might be that you have to swap the order of basic auth and openid authC domains in config.yml.

**Comment by JordanBarnartt** [comment]
Thanks for pointing that out, @derek-ho, I missed the part about the importance of the ordering.

I switched things around, so now my `config.yml` looks likes:
```yaml
  authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: username
            roles_key: roles
            openid_connect_url: https://example.com/oidc/<client_id>/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

However, whenever I attempt to sign in using SSO, I get the response `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`.  There's no logs in Opensearch itself, and Dashboards logs just repeat the 401 message.

If, in my `config.yml` file, I switch the value of the `order` keys (so basic is 1 and openid is 0), I am able to log in fine.  Given this, I don't think it's an issue with our role mappings.

I tried disabling multiple auth in our `opensearch_dashboards.yml` file to have only openid auth, but that didn't change anything.

Do you have any idea what the issue might be?

**Comment by derek-ho** [comment]
@JordanBarnartt is your full opensearch_dashboards.yml shared here: https://github.com/opensearch-project/security-dashboards-plugin/issues/2114#issue-2506545856? If so I think you might be missing `opensearch.username` and `opensearch.password`, which is what OSD would use for that internal OpenSearch Dashboards server user auth.

**Comment by JordanBarnartt** [comment]
Okay, that solved the "unauthorized" issue.  My config.yml file is now:
```yaml
authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: username
            roles_key: roles
            openid_connect_url: https://example.com/oidc/<client_id>/.well-known/openid-configuration
        authentication_backend:
          type: noop
```

However, we're back to the original issue, unfortunately.  Every 5 minutes, regardless of activity, an OpenID user gets pushed back to the login screen.
