### ISSUE TITLE
Visualizations sometime fail with a 403 forbidden

### ISSUE THREAD

**Issue by remioo** [opensearch-project/security-dashboards-plugin#219]
I am using opendistro 1.4.0 (via the docker image) to visualise metricbeat data.
When I load a dashboard, sometimes one or 2 visualizations fail with a 403 error.
If I reload the dashboard everything loads well, or sometimes other visualizations fail.
This seem to be related to the wrong tenant being requested: the global_tenant while it is deactivated. My user has the read permissions for the requested index.

The returned message is the following:
`{"message":"no permissions for [indices:data/read/search] and User [name=adv_supervisor, backend_roles=[], requestedTenant=null]: [security_exception] no permissions for [indices:data/read/search] and User [name=adv_supervisor, backend_roles=[], requestedTenant=null]","statusCode":403,"error":"Forbidden"}`

The logs are the following:
`{"type":"response","@timestamp":"2020-06-02T00:50:54Z","tags":[],"pid":1,"method":"get","statusCode":403,"req":{"url":"/api/saved_objects/_find?fields=title&fields=fields&search=%22metricbeat-*%22&search_fields=title&type=index-pattern&per_page=20&page=1&default_search_operator=OR","method":"get","headers":{"host":"192.168.56.105:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://192.168.56.105:5601/app/kibana","kbn-version":"7.4.2","content-type":"application/json","connection":"keep-alive","securitytenant":"advanced_tenant"},"remoteAddress":"192.168.56.108","userAgent":"192.168.56.108","referer":"https://192.168.56.105:5601/app/kibana"},"res":{"statusCode":403,"responseTime":207,"contentLength":9},"message":"GET /api/saved_objects/_find?fields=title&fields=fields&search=%22metricbeat-*%22&search_fields=title&type=index-pattern&per_page=20&page=1&default_search_operator=OR 403 207ms - 9.0B"}`

And in the elasticsearch logs I have this message:
`Tenant global_tenant is not allowed for user bk_adv_supervisor`

My tenants parameters are:
```
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.enable_global: false
opendistro_security.multitenancy.tenants.enable_private: false
```

My role is defined this way:
```
advanced_supervisor:
  reserved: true
  index_permissions:
    - index_patterns:
      - "metricbeat-*"
      allowed_actions: 
        - read
        - indices_monitor
  tenant_permissions:
    - tenant_patterns:
      - "advanced_tenant"
      allowed_actions:
        - kibana_all_read
```

As a workaround, it seem if I add global_tenant to the tenant_patterns I don't have the issue anymore
