### ISSUE TITLE
[BUG] Only JWT authentication was intended to be used, but Basic Auth is still allowed

### ISSUE THREAD

**Issue by 10000-ki** [opensearch-project/security-dashboards-plugin#2206]
**What is the bug?**

OpenSearch Security is configured to use **only JWT authentication**, without enabling multi-auth:

```yaml
### auth type
opensearch_security.auth.type: "jwt"
opensearch_security.jwt.enabled: true
# now you can authn like 'http://localhost:5601?jwt={jwt_value}'
opensearch_security.jwt.url_param: "jwt"
```

Even though JWT is the only configured authentication method, if a user accesses OpenSearch Dashboards using the following URL:

https://{osd-url}:5601/app/home#/

and includes an Authorization header with Basic Auth credentials (e.g., Authorization: Basic YWRta211W46MTIzNA==) without providing a JWT token, the login is still successful.

**How can one reproduce the bug?**

**What is the expected behavior?**

- Only JWT-based authentication should be allowed.
- Any request without a valid JWT token should be rejected.

**What is your host/environment?**
 - Version : 2.18.0
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.
