### ISSUE TITLE
Kibana not handling SAML token expiration?

### ISSUE THREAD

**Issue by m-mcleod** [opensearch-project/security-dashboards-plugin#225]
I'm seeing an issue with SAML authentication to my ODFE cluster.  The authentication works great at the opening of a session.  I'm routed to the idp, log in, and am directed into Kibana. 

After using Kibana for an hour (the exiration time for the SAML token), Kibana will pop up a basic authentication prompt.  If I enter anything (other than the internal user creds) and hit 'sign in' I'll get the Kibana SAML error page and cannot recover without deleting cookies.  If I hit 'cancel', I'm directed to a json text 401 error message.  Again, I cannot get back into Kibana without deleting cookies.

It seems like Kibana is unable to recognise when the SAML expiration occurs.  Elasticsearch correctly throws back a 401 on a request and Kibana doesn't handle it by directing you to the flow needed to get a new token.

The relevant parts of my kibana.yml (I don't have ttls or keepAlive set, although I have tested several configurations of those parameters without success):
```
opendistro_security.auth.type: "saml"
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
```

The relevant parts of my config.yml:
```

  authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://my.metadata.url
              entity_id: my.entity.id
            sp:
              entity_id: my_odfe
            kibana_url: https://kibana.url
            exchange_key: '32randomchars'
        authentication_backend:
          type: noop
```
