### ISSUE TITLE
Kibana won't connect to ElasticSearch if SSL verification is required

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [opensearch-project/security-dashboards-plugin#239]
Basic info:
 - ElasticSearch and Kibana versions: 7.7.0, OpenDistro plugin versions: 1.8.0.0
 - All components are running in docker containers managed with docker-compose

I followed the guide (https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/generate-certificates/) for generating self-signed certificates. When I get to the end, there is a section for configuring Kibana (https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/generate-certificates/#kibana). It says there are two choices: "Disable SSL verification" or "Add the root CA". I went with the "Add root CA" option, but it doesn't seem to work, I get output that looks like this:
```
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["error","elasticsearch","monitoring"],"pid":7,"message":"Request error, retrying\nGET https://esserver:9200/_xpack => self signed certificate"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nHEAD https://esserver:9200/.apm-custom-link => self signed certificate"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nHEAD https://esserver:9200/.apm-agent-configuration => self signed certificate"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["error","elasticsearch","monitoring"],"pid":7,"message":"Request error, retrying\nGET https://esserver:9200/_xpack => self signed certificate"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nGET https://esserver:9200/_xpack => self signed certificate"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"Unable to revive connection: https://esserver:9200/"}
kibserver_1        | {"type":"log","@timestamp":"2020-06-09T19:22:20Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"No living connections"}
```

Even after I downgraded the verification mode to "certificate", I still see the above errors.

My Kibana config file:

```yaml
server:
    name: "kibserver"
    host: "kibserver"
elasticsearch.hosts: "https://esserver:9200"
elasticsearch.requestTimeout: 200000
elasticsearch.shardTimeout: 200000
elasticsearch.startupTimeout: 60000
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/root-ca.pem"]
elasticsearch.ssl.verificationMode: certificate
elasticsearch.ssl.certificate: "/usr/share/kibana/config/admin.pem"
elasticsearch.ssl.key: "/usr/share/kibana/config/admin-key.pem"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "MyPassword"
xpack.security.enabled: false
monitoring.enabled: true
opendistro_security.allow_client_certificates: true
monitoring.ui.elasticsearch.ssl.verificationMode: "certificate"
monitoring.ui.elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/root-ca.pem"]
monitoring.ui.elasticsearch.username: "kibanaserver"
monitoring.ui.elasticsearch.password: "MyPassword"
```

If I set the verificationMode (both of them) to "None", then I am able to access Kibana without any problems.

Are there any other config settings I need to set that aren't in the documentation?
