### ISSUE TITLE
Bug with Kibana async_search permissions

### ISSUE THREAD

**Issue by fenneh** [opensearch-project/security-dashboards-plugin#274]
Running OSS ELK 7.8.0 using the OpenDistro security plugins.

Hit a pretty damning bug - when attempting to view any data in Kibana via the Discover pages you're hit with the following:

```
[security_exception] no permissions for [indices:data/read/async_search/submit] and User........
```

The permission isn't accessible within the Kibana UI, I've attempted to use the API to grant the permission but that also does not work (despite being visible in the UI)

```
PUT _opendistro/_security/api/roles/opendistro_security_anonymous
{
    "cluster_permissions" : [
      "indices:data/read/search",
      "indices:admin/mappings/get",
      "indices:admin/aliases/get",
      "indices:data/read/*"
    ],
    "index_permissions" : [
      {
        "index_patterns" : [
          "apm*",
          "logstash*",
          "filebeat-*",
        ],
        "dls" : "",
        "fls" : [ ],
        "masked_fields" : [ ],
        "allowed_actions" : [
          "crud",
          "create_index",
          "indices:data/read/async_search/submit"
        ]
      }
    ],
    "tenant_permissions" : [
      {
        "tenant_patterns" : [
          "DevOps"
        ],
        "allowed_actions" : [
          "kibana_all_write"
        ]
      },
      {
        "tenant_patterns" : [
          "global_tenant"
        ],
        "allowed_actions" : [
          "kibana_all_write"
        ]
      }
    ]
}
```

Async search was added in 7.7.0. This bug has been fixed by the SearchGuard guys - https://forum.search-guard.com/t/indices-data-read-async-search-submit-error/1842

Reported by another user on the OpenDistro forums; https://discuss.opendistrocommunity.dev/t/bug-indices-data-read-async-search-submit-error/3031

Is there any workarounds without granting users `all_access` to clusters?

**Comment by fenneh** [comment]
Any updates regarding this? This must be breaking for anyone using Elastic's Kibana with the OpenDistro Security plugin.

**Comment by SurgeVortex** [comment]
This is affecting my cluster too.

**Comment by SurgeVortex** [comment]
This is what the searchguard guys did to fix the issue. Can you please provide a similar fix?
[Override Kibana internal search](https://git.floragunn.com/search-guard/search-guard-kibana-plugin/-/commit/7ce4a00ef41cb69dbb859a6afb74b56e14e30bb2)

**Comment by Vhartmannfigaro** [comment]
Waiting for a bug correction i rollback to elastic search 7.6.1, Kibana 7.6.1 and open distro 1.7.0.0 plugin and with this configuration it works. _async_search is new in 7.7. That's my configuration:

In Internal_users.yml:
```
readonly_user:
  reserved: false

In roles_mapping.yml:
read_only_index:
  users:
  - readonly_user
kibana_RO:
  users:
  - readonly_user
kibana_read_only:
  users:
  - readonly_user
```

In roles.yml:
```
kibana_RO:
  reserved: true
  hidden: false
  description: Provide the minimum permissions for a kibana user
  cluster_permissions:
  - cluster_composite_ops
  index_permissions:
  - index_patterns:
    - ".kibana"
    - ".kibana-6"
    - ".kibana_*"
    allowed_actions:
    - read
    - delete
    - manage
    - index
  - index_patterns:
    - ".tasks"
    - ".management-beats"
    - "*:.tasks"
    - "*:.management-beats"
    allowed_actions:
    - indices_all
  tenant_permissions:
  - tenant_patterns:
    - global_tenant

```

In kibana.yml:
```
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opendistro_security.multitenancy.enabled: false
opendistro_security.multitenancy.tenants.enable_global: true
opendistro_security.multitenancy.tenants.enable_private: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.multitenancy.enable_filter: false


opendistro_security.readonly_mode.roles: [“kibana_read_only”]

```
