### ISSUE TITLE
Can't create index pattern when using index permissions on roles

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security-dashboards-plugin#598]
I've have indices like prodapps-yyyyMMdd, prodother-yyyMMdd and prodsystem-yyyMMdd
I want to hide prodsystem* indices to users so i created a role myrole like 
```
myrole:
  index_permissions:
  - index_patterns:
    - "/^(?!prodsystem).*/"
    allowed_actions:
    - "*"
  - index_patterns:
    - "prodsystem*"
    allowed_actions:
    - "indices:data/read/field_caps*"
    - "indices:data/read/search*""`
````

When user mapped to the role wants to create an index_pattern prodsystem*, indices are not shown and he can create prodapp* index pattern ==> Good
BUT index pattern prod* can not be created because of  `No index-level perm match for User ... [Action [indices:admin/resolve/index]] error`
I added this permission to the role but now user has access to prodsystem* indices in index pattern and discovery
