### ISSUE TITLE
Bug: Choosing tenant works inconsistent with OIDC authc (and LDAP authz)

### ISSUE THREAD

**Issue by oscarkraemer** [opensearch-project/security-dashboards-plugin#701]
I have previously used LDAP for authentication and authorisation. Now that I’m moving authentication to OIDC (but keep authorisation in LDAP) I noticed an inconsistency between the implementations.

When everything was in LDAP:
When one logs in, one get prompted by the “Select your tenant” form.

When authentication with OIDC:
I do not get prompted by the “Select your tenant” form instead my “Private” tenant is already configured for me (as it is configured in  kibana.yml `opendistro_security.multitenancy.tenants.preferred`).

What I expected:
I expected to be prompted by the “Select your tenant” when I log into Kibana.

snippet from my current config.yml
```
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 8
        http_authenticator:
          type: "openid"
          challenge: false
          config:
            subject_key: yaddayadda
            openid_connect_url: yaddayadda
            enable_ssl: true
            verify_hostnames: true
        authentication_backend:
          type: "noop"
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        order: 7
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "ldap"
          config:
......          
     authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: "ldap"
          config:
.....
 ```
 
 Kibana rpm version: `opendistroforelasticsearch-kibana-1.12.0-1.x86_64`
