### ISSUE TITLE
Anonymous user for Kibana and ElasticSearch in ODFE 1.11.0

### ISSUE THREAD

**Issue by sanacl** [opensearch-project/security-dashboards-plugin#741]
Hi all,

I'd like to get anonymous user both for ES and Kibana with ODFE 1.11.0. As far as I saw, the instructions at opendistro-for-elasticsearch/security#42 are obsolete so I tried to adapt them for 1.11.0 with no luck. This is what I tried:

1. In config.yml enable anonymous access. 
```
  dynamic:
    http:
      anonymous_auth_enabled: true
```
2. Created anonymous role with required permission at roles.yml (_this is what needed to be changed_)
```
opendistro_security_anonymous:
  reserved: true
  cluster_permissions:
    - 'CLUSTER_COMPOSITE_OPS_RO'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices:data/read*'
        - 'indices:admin/mappings/fields/get*'
 ```
 3. Created role mapping for opendistro_security_anonymous_backendrole role at roles_mapping.yml file

```
opendistro_security_anonymous:
  backend_roles:
  - "opendistro_security_anonymous_backendrole"
```
4. Executed securityadmin tool to apply changes
5. Updated kibana.yml to enable anonymous access for kibana (and restarted)
```
# Anonymous access
opendistro_security.auth.anonymous_auth_enabled: true
```
--- 

The result is I can read the `.kibana` index querying the cluster but I still see the login page in Kibana. 

Thanks for your help!
