### ISSUE TITLE
[BUG/Documentation] Example of Keycloak authentication

### ISSUE THREAD

**Issue by kafonek** [opensearch-project/security-dashboards-plugin#806]
I have not been able to configure Opensearch / Opensearch Dashboards 1.0.0 to authenticate with Keycloak.  I believe this is primarily a documentation issue, but there may be a bug somewhere in the code.  

**To Reproduce**
1. Deploy Opensearch/Opensearch Dashboard using `docker-compose` similar to https://github.com/opensearch-project/opensearch-build/blob/main/release/docker/dockercomposefiles/docker-compose.yml

2. Mount custom `config.yml` and `opensearch_dashboards.yml` into the containers.  _Note: I'm referencing a corporate Keycloak instance here, I understand that doesn't make the setup easy to reproduce.  Sorry.  If you have a public openid-connect set up, like Okta, that should work for an example? _

```
# /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
# mounted in the opensearch node container

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false

    authc:
      basic:
        description: "Basic user/pw"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal

      keycloak:
        description: "Log in with Keycloak"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://my.keycloak/auth/realms/my-realm/.well-known/openid-configuration
            verify_hostnames: false
        authentication_backend:
          type: noop
```

```
# /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
# mounted into opensearch-dashboards container

server.host: "0"
opensearch.hosts: ["https://opensearch:9200"]
opensearch.ssl.verificationMode: none
opensearch.username: "kibanaserver"
opensearch.password: "kibanaserver"
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
# Use this setting if you are running opensearch-dashboards without https
opensearch_security.cookie.secure: false


opensearch_security.auth.type: "openid"
opensearch_security.openid.connect_url: "https://my.keycloak/auth/realms/my-realm/.well-known/openid-configuration"
opensearch_security.openid.client_id: "opensearch"
opensearch_security.openid.client_secret: "abc123..."
opensearch_security.openid.scope: "openid"
opensearch_security.openid.base_redirect_url: "http://opensearch-host-machine:5601"
```

**Expected behavior**
I navigate to the Dashboard UI and get redirected to Keycloak.  Unfortunately it returns a `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`

**Plugins**
```
[opensearch@332d5e6fcb49 bin]$ ./opensearch-plugin list
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-notebooks
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql
```

```
[opensearch-dashboards@31d9b78a27dd bin]$ ./opensearch-dashboards-plugin list
alertingDashboards@1.0.0.0-rc1
anomalyDetectionDashboards@1.0.0.0-rc1
ganttChartDashboards@1.0.0.0-rc1
indexManagementDashboards@1.0.0.0-rc1
notebooksDashboards@1.0.0.0-rc1
queryWorkbenchDashboards@1.0.0.0-rc1
reportsDashboards@1.0.0.0-rc1
securityDashboards@1.0.0.0-rc1
traceAnalyticsDashboards@1.0.0.0-rc1
```

**Host/Environment (please complete the following information):**
https://hub.docker.com/r/opensearchproject docker images
